<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Exceptions\**" />
    <EmbeddedResource Remove="Exceptions\**" />
    <None Remove="Exceptions\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.1.0" />
    <PackageReference Include="FluentValidation" Version="12.1.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0" />
    <PackageReference Include="MediatR" Version="13.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Clipr.Modules.Upload.Domain\Clipr.Modules.Upload.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Behaviors\" />
  </ItemGroup>

</Project>
