<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Upload\Clipr.Modules.Upload.Domain\Clipr.Modules.Upload.Domain.csproj" />
      <ProjectReference Include="..\Clipr.Modules.User.Domain\Clipr.Modules.User.Domain.csproj" />
    </ItemGroup>

</Project>
